### ISSUE TITLE
建议添加来源

### ISSUE THREAD

**Issue by zjcfynn** [blackmatrix7/ios_rule_bot#1]
https://raw.githubusercontent.com/lhie1/Rules/master/Surge/Surge%203/Provider/Media/YouTube.list这个是洞主的规则，我之前一直使用这个；还可以

**Comment by blackmatrix7** [comment]
谢谢提供规则，已加入。另外，已经把规则合并到https://github.com/blackmatrix7/ios_rule_script，这个项目当时是用来做测试的，后面会删掉。
