### ISSUE TITLE
建议增加原数据以及删除testflight相关条目

### ISSUE THREAD

**Issue by zjcfynn** [blackmatrix7/ios_rule_bot#2]
https://raw.githubusercontent.com/lhie1/Rules/master/Surge/Surge%203/Provider/Proxy.list 这个是洞主的相关规则；建议加入。
另外testflight相关的条目可以删除，因为如果和Apple其他的条目网络ip地区不同可能会产生不可预期的问题

**Comment by blackmatrix7** [comment]
谢谢提供规则，已加入。TestFlight暂时还是保留，因为部分地区出现无法访问TestFlight的问题。另外，已经把规则合并到https://github.com/blackmatrix7/ios_rule_script，这个项目当时是用来做测试的，后面会删掉。
